### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by boberski666** [xevidos/codiad#5]
I use php 7.3 on my server and when I try to isntall ide I get that mysql packae is unavailable but it is not true. 

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
php7.3-mysql is already the newest version (7.3.13-1+ubuntu16.04.1+deb.sury.org+1).
```

Also when I enter all the correct data install process creates config file but no database.
Anybody chae idea why?

**Comment by boberski666** [comment]
I get an error when I try to install database:

Specified key was too long; max key length is 3072 bytes

**Comment by xevidos** [comment]
Hello,

We are currently beta testing our next update that removes the extra long keys from tables.  If you would like to download the development branch and install that way you can.  The fixes should be included in the next release.  Another option that is a currently used workaround is to force the database into latin1 charset mode instead of whatever default the current database is created in.

**Comment by xevidos** [comment]
The extra long keys have been removed in 3.0 update
